### ISSUE TITLE
post-deploy didn't use environment variables

### ISSUE THREAD

**Issue by josser** [Unitech/pm2-deploy#102]
Hi! 
Not sure if bug but.. 

So, there is  "env"  : {  ...   } block in every deploy targets in ecosystem.json but even if something is specified there, it doesn't applied to post-depoy command hook. 

Here is use-case: I have post-deployment scripts, i.e migrations which have to be executed before application is started just after deploy. And this scripts  are using same config system which takes db connection credentials from env variables. 

It would be great if env variables from ecosystem will be injected not only for apps but for all hooks too. 

Thank you and sorry for bad english

**Comment by digital-flowers** [comment]
you can do this until they fix it

```
"post-deploy": "export NODE_ENV=production && yarn install && npm run bundle && npm run db:update && pm2 reload ecosystem.config.js --env production"
```

**Comment by phra** [comment]
i think that the problem can be around this line: https://github.com/Unitech/pm2-deploy/blob/master/deploy.js#L16

if i have time i will try to debug it.
it seems to me that the environment variable are not being passed to the shell command being executed.

**Comment by negamaxi** [comment]
Similar problem here. `pm2 deploy my_server` wasn't able to start app with nvm (`[PM2][ERROR] NVM is not available in PATH`). I have to `export NVM_DIR=/home/me/.nvm` in post-deploy script. When I execute `pm2 start ecosystem.config.js` from my_server shell NVM_DIR variable works as expected.

**Comment by phra** [comment]
sorry i forgot to check this bug. if i can i will try in these day to fix the issue.

**Comment by phra** [comment]
i finally had time to debug the issue. i've added a way to pass the env declared in each `<env>` in the `deploy` section. let's have a look at #152 and start a discussion about this feature.
