### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by BrandonCopley** [Unitech/pm2-deploy#104]
Is there a way to restart the servers without pushing a new deploy? we maintain quite a few servers and sometimes we just want to restart the processes without having to ssh into the servers or pushing new code.

**Comment by sbmelvin** [comment]
@BrandonCopley 
Have you tried one of the reload/restart commands listed on the [related commands](http://pm2.keymetrics.io/docs/usage/deployment/#related-commands) page?

```
$ pm2 startOrRestart all.json            # Invoke restart on all apps in JSON
$ pm2 startOrReload all.json             # Invoke reload
$ pm2 startOrGracefulReload all.json     # Invoke gracefulReload 
```

**Comment by BrandonCopley** [comment]
I had not, this works well. Thanks!
