### ISSUE TITLE
Post deploy script fails with permission denied.

### ISSUE THREAD

**Issue by flodev** [Unitech/pm2-deploy#11]
Hi,
I tried to use a custom post-deploy.sh file and added it to my ecosystem file with absolute path.
It always fails with permission denied. I'm using a deploy user on ubuntu but have tried it for testing purposes as root. The same.
`bash: /usr/share/nginx/www/myproject/current/post-deploy.sh: Permission denied`

I think its related to the logic happen in the hook()-function defined in the deploy script.

**Comment by gajus** [comment]
I am still lost.

My post-deploy script is defined as:

```json
"post-deploy": "bash ./post-deploy-production.sh"
```

my `./post-deploy-production.sh` is:

```sh
#!/bin/sh
nvm use v5.1.0;
```

I am getting an error:

```
./post-deploy-production.sh: line 2: nvm: command not found
```

Note, that if I write:

```json
"post-deploy": "nvm use v5.1.0"
```

it works as expected.

**Comment by gajus** [comment]
@Unitech Is this something that needs to/can be fixed at a script level or at pm2-deploy level?

**Comment by gajus** [comment]
Found the answer in http://unix.stackexchange.com/q/184508/36805.

```sh
source ~/.nvm/nvm.sh
nvm
```

makes it work.

**Comment by gajus** [comment]
or I can simply use:

```json
"post-deploy": "source ./post-deploy-production.sh"
```

and then keep `./post-deploy-production.sh` as:

```sh
nvm
```
