### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by nonedeactivated** [Unitech/pm2-deploy#113]
I'm having an issue here using my MacOS El Capitan

**Last login: Wed Dec 21 16:02:28 on ttys001
mac-air:loadwallet-rest pmgcti$ sudo pm2 deploy deploy.json sandbox update --force
Password:
--> Deploying to sandbox environment
--> on host 52.221.223.218
  ○ deploying origin/master
  ○ executing pre-deploy-local
  ○ hook pre-deploy
  ○ fetching updates
bash: line 0: cd: /Users/pmgcti/Documents/cti/project/master/loadwallet/loadwallet-rest/~/loadwallet-rest/source: No such file or directory

  fetch failed

Deploy failed
mac-air:loadwallet-rest pmgcti$** 

I beleive the "bash: line 0..." code supposed to be in the ec2. 
Can someone help me please? Thanks in advance

**Comment by riccardodegan-geekcups** [comment]
In file deploy.json at the ```path``` key (```"path" : "~/loadwallet-rest/source" )```,  set the absolute path, not relative. It work for me.

**Comment by nonedeactivated** [comment]
Yes it works. I found out that relative path won't work. Thanks

**Comment by kounelios13** [comment]
@riccardodegan-geekcups  I have specified the absolute path but still get errors for `sourc` directory.Only sollution was to manually create the source directory before deploying
