### ISSUE TITLE
Error on production setup

### ISSUE THREAD

**Issue by Jabark** [Unitech/pm2-deploy#116]
Hi, I'm hosting a Ghost blog on a Linux Azure VM, but I'm having trouble setting up PM2 deploy.

The issue I'm getting:
![image](https://cloud.githubusercontent.com/assets/9607853/21452433/bfd08d5a-c8fe-11e6-90ab-fc6ba30bee66.png)

My ecosystem.json settings (in the root of the app):

```
{
  "apps": [
    {
      "name"    : "StoreFeeder Web",
      "script"  : "index.js",
      "env": {
        "COMMON_VARIABLE": "true"
      },
      "env_production" : {
        "NODE_ENV": "production"
      }
    }
  ],
  "deploy" : {
    "production" : {
      "user" : "storefeeder",
      "host" : "13.81.54.188",
      "ref"  : "origin/master",
      "repo" : "git@github.com:StoreFeeder/storefeeder-web-v3.git",
      "path" : "apps/ghost/htdocs",
      "post-deploy" : "npm install && pm2 startOrRestart ecosystem.json --env production"
    },
    "dev" : {
      "user" : "node",
      "host" : "212.83.163.1",
      "ref"  : "origin/master",
      "repo" : "git@github.com:repo.git",
      "path" : "/var/www/development",
      "post-deploy" : "npm install && pm2 startOrRestart ecosystem.json --env dev",
      "env"  : {
        "NODE_ENV": "dev"
      }
    }
  }
}
```

I'm about as Linux savvy as a teaspoon so I'm almost certain that I'm the issue and not PM2.

I've been doing the setup on the server with Putty as I'm on a Windows machine myself.

I have setup ssh keys both in GitHub and in `.ssh`, however I'm aware I could have set this up incorrectly. Would a "command not found" error indicate issues with keys? From what I gather a specific message should tell me if this was the case.

Any help appreciated.

**Comment by Unitech** [comment]
Hello, install git on your remote server
