### ISSUE TITLE
avoid fetching tags when deploying

### ISSUE THREAD

**Issue by phra** [Unitech/pm2-deploy#123]
hi,

as next improvement for decreasing deploy timings I suggest to remove from this [line](https://github.com/Unitech/pm2-deploy/blob/master/deploy#L238) the flags `--all --tags` because are IMHO useless and they slow down the deploy itself. (it makes no sense to set in the ecosystem a tag reference, isn't it?)

what do you think guys?
as always I can prepare a PR if you agree on this change.

**Comment by vmarchaud** [comment]
Do what you think is better without breaking backward compatibility, the deploy system is old and planned to be replaced by https://github.com/vmarchaud/deployerjs when it will be finished.
So yeah feel free to make a PR and ping us on it.
