### ISSUE TITLE
Any chance on SVN support?

### ISSUE THREAD

**Issue by jbhue** [Unitech/pm2-deploy#134]
I use PM2 on my servers and I really enjoy the tool. I would love to take advantage of the pm2 deployment feature but my company uses SVN and not GIT. Are there plans to ever support checkout out from an SVN repository as opposed to cloning a GIT repo? Thanks.

**Comment by vmarchaud** [comment]
Not currently with this tool. Maybe in the future with [deployerjs ](https://github.com/vmarchaud/deployerjs)
