### ISSUE TITLE
Single app deployment/restart

### ISSUE THREAD

**Issue by mjansing** [Unitech/pm2-deploy#135]
Hey folks,

i use pm2 to deploy a bunch of node services to a remote hosts. These services are managed in a single git repository. Is there a way to trigger a new deployment and only restart specific services (the updated ones)?

Currently i use a post-deploy hook with `pm2 startOrRestart ecosystem.json` which restarts all declared apps. This issue maybe corresponds with https://github.com/Unitech/pm2-deploy/issues/132

**Comment by phra** [comment]
you can use [startOrReload](http://pm2.keymetrics.io/docs/usage/deployment/#related-commands) if all of your application are running in cluster mode to achieve 0s downtime during the deploy.

closing this in favor of #132
