### ISSUE TITLE
Is it forbidden to deploy a branch name has slashes?

### ISSUE THREAD

**Issue by daiwhea** [Unitech/pm2-deploy#139]
https://github.com/Unitech/pm2-deploy/blob/a3398fdd56afb39a43039a7864635688843b39e6/deploy#L210

I have a branch named as  origin/deploy/test . When I want to setup for a new server. It keeps complain:

```
Cloning into '/data/web/xxxx/source'...
warning: Could not find remote branch test to clone.
fatal: Remote branch daiwhea not found in upstream origin
```

Can I deploy a branch which name containes slashes[/] ? 

Change the code above to **local branch=${ref#*/}** will be ok.

Thanks.

**Comment by vmarchaud** [comment]
Feel free to make a PR so we can publish the fix :)

**Comment by phra** [comment]
yep, i think we can fix this.
