### ISSUE TITLE
Allow `setup` step to be called multiple times

### ISSUE THREAD

**Issue by pke** [Unitech/pm2-deploy#186]
I have the problem from CI that I don't know if `pm2 deploy` has already been called with `setup`. Calling it a second time currently results in an error when it tries to clone the repo:

```bash
Local PM2 version: 4.2.0

  ○ hook pre-setup
  ○ running setup
  ○ cloning git@deployment:pke/xstate.io.git
  ○ full fetch
fatal: destination path '/var/www/restlr.io/source' already exists and is not an empty directory.

  failed to clone

Deploy failed
```

Would it be possible to gracefully ignore this if the directory already exists?

**Comment by Unitech** [comment]
just make sure that dest is not already there
