### ISSUE TITLE
wrong shared folder after setup

### ISSUE THREAD

**Issue by enkows** [Unitech/pm2-deploy#19]
After run `pm2 deploy env setup`, it makes wrong shared folder like this:

```
|-- myapp
    |-- {shared
        |-- {logs,pids},source}
```

Ubuntu 14.04.1 LTS
Node v0.10.32
pm2 0.10.8

**Comment by mchicote** [comment]
Same here.
I was expecting the following folders:
````
/myapp/shared
/myapp/shared/logs
/myapp/shared/pids
/myapp/source
````

**Comment by mchicote** [comment]
@Unitech I think this was caused by using `sh` instead of `bash`

**Comment by roderik** [comment]
I'm experiencing the same issue. The user i'm deploying with has a shell of bash.

**Comment by membrive** [comment]
Same problem here. I am using Ubuntu 14.04, Node.js v8.9.3 and PM2 2.9.1.

**Comment by phra** [comment]
@membrive did you check @marcoschicote comment?

**Comment by membrive** [comment]
@phra yes, sorry for the delay. Using `bash` solves the problem.

**Comment by phra** [comment]
ok, so closing this.

**Comment by luffs** [comment]
I ran into this problem and solved it by changing the default shell for my deploy user on the target server with `chsh -s /bin/bash <username>`
