### ISSUE TITLE
nvm not loaded

### ISSUE THREAD

**Issue by Raffiki** [Unitech/pm2-deploy#33]
I work with nvm to load node and npm.

to use these binaries in the post-deploy hook (with the nvm user of course), the PATH seemed not to be set.

```
command not found: npm
```

a quick fix was for me to add the bin dir to the PATH, as:

```
 "post-deploy" : "export PATH=$PATH:/home/raf/.nvm/v0.10.34/bin/ && npm rebuild && pm2 startOrRestart ecosystem.json --env dev",
      env  : {
        NODE_ENV: "dev"
      }
```

This worked, but I doubt this is the recommended way. Anyone a suggestion how this fix can be avoided?

**Comment by josser** [comment]
Guys, I have same issue but with zsh. 
I've moved .nvm init lines to the top of .zshrc but this doesn't help.
Is there anything I can do not switching to bash? Thank you!

**Comment by vinaynb** [comment]
@josser facing the same issue. Any solution ?

**Comment by josser** [comment]
@vinaynb Oh, I'm just checked my ecosystem.json and I see that I'm able to use npm in post-deploy hooks but I'm totally can't remember what I've done to fix this.

**Comment by KoteKotlyarov** [comment]
What if I didn't have next files in *~*:
.bash_profile
.profile
.bashrc

And still pm2 deploy cant see nor *nvm*, nor *pm2*, nor *node* on server...

There is no nvm on system (I cant test it with nvm for now. This is production server, so I don't want to make any downtime by reinstalling node/npm/pm2 with HomeBrew or anything else. Just want a workaround for this situation)


OS: Mac 10.12.2

```
node -v
v5.6.0
```

```
npm -v
3.6.0
```

```
which npm
/usr/local/bin/npm
```

```
which pm2
/usr/local/bin/pm2
```

```
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

PM2 deploy log (partly):
```
○ executing post-deploy `npm install`
bash: npm: command not found
```

```
○ executing post-deploy `/usr/local/bin/npm install`
env: node: No such file or directory
```

I also tried to export npm in $PATH in post-deploy or .bash_profile / .bashrc but with no success

What I need to do to fix this issue ?

**Comment by ginus** [comment]
@josser @vinaynb @Unitech 
I exec command below:
```
pm2 deploy staging exec "echo $NVM_DIR"
--> Deploying to staging environment
--> on host 121.196.207.137
/Users/art/.nvm
--> Success
```
it is the local value not but server value of $NVM_DIR, see that, if I use ssh login server side and exec "echo $NVM_DIR"
```
➜  ~ echo $NVM_DIR
/root/.nvm
```
so if any solution ?
