### ISSUE TITLE
current link useless ???

### ISSUE THREAD

**Issue by menems** [Unitech/pm2-deploy#38]
I don't understand why there is a current link  to source directory if we alway reset our applications in the source folder??

Secondly it will be nice if we can use the refs parameters  in command line?

and have cd $path/sources/$refs/ && git reset ....&& post-install && ln -sf $path/sources/$refs current

Hope i am enought clear?

**Comment by jasson15** [comment]
+1 with `current` and `source`

**Comment by boneskull** [comment]
fwiw I can't see any use for `current` either

**Comment by vmarchaud** [comment]
As i said in #72, other tool use this, the aim is to have somewhat a standard symlink that go into source folder.
