### ISSUE TITLE
Cannot clone the repo via pm2 deploy

### ISSUE THREAD

**Issue by chenweiyj** [Unitech/pm2-deploy#40]
I can git clone my repo in the server ssh terminal. However, when I use `pm2 deploy ecosystem.json dev setup` to setup my project, it shows the following message.

```
Initialized empty Git repository in /home/imfoyo/deploy/shb0577/development/source/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

  failed to clone

Deploy failed
```

My `ecosystem.json` file is as follows:
```
{
  /**
   * This is a sample configuration file for PM2
   */

  /**
   * Here we declare the apps that must be managed by PM2
   * All options are listed here:
   * https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#json-app-declaration
   *
   */
  apps : [

    // First application
    {
      name      : "myrepo",
      script    : "bin/www",
      env: {
        COMMON_VARIABLE: "true"
      },
      env_production : {
        NODE_ENV: "production"
      }
    }

  ],


  /**
   * PM2 help you to deploy apps over your servers
   * For more help go to :
   * https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#deployment-pm2--090
   */
  deploy : {
    production : {
      user : "imfoyo",
      host : "192.168.199.174",
      ref  : "origin/master",
      repo : "git@bitbucket.org:belife/myrepo.git",
      path : "/var/www/production",
      "post-deploy" : "pm2 startOrRestart ecosystem.json --env production"
    },
    dev : {
      key  : "/home/imfoyo/.ssh/imfoyo.lan",
      user : "imfoyo",
      host : "192.168.199.174",
      ref  : "origin/master",
      repo : "git@bitbucket.org:belife/myrepo.git",
      path : "/home/imfoyo/deploy/development",
      "post-deploy" : "npm install && pm2 startOrRestart ecosystem.json --env dev",
      env  : {
        NODE_ENV: "dev"
      }
    }
  }
}
```

**Comment by Unitech** [comment]
```
Permission denied (publickey).
```

Your remote server is not allowed to git clone (you forgot to add your server public key to bitbucket)

**Comment by chenweiyj** [comment]
@Unitech My server is centos. I don't know why each time I login to the server, I should manually run 
```
$ eval `ssh-agent -s`
$ ssh-add /path/to/mykey
```

However, if I put these commands to my `.bashrc` file, `scp` will not work.

**Comment by alecho** [comment]
I'm having the same issue I think. I'm sure it's something on my end I need to fix. Did you ever figure out what it was for you?

**Comment by Sk1Zy** [comment]
I'm also having this problem. Get permission denied. I'm able to remote into my ssh server and clone from there no problem, don't have to type in a password or anything like that. But when i run the deploy script using the same user on the remote machine i get this permission denied.

**Comment by alecho** [comment]
You need to use a key that doesn't have a passphrase. I ended up creating a `~/.ssh/config` with so that I could use different keys for different Github projects.

**Comment by Sk1Zy** [comment]
In my case i was deploying to the same server that my git installation was on. When i tried to deploy to a different server it worked immediately.

**Comment by lsiden** [comment]
I am having the same problem.
Does the "key": parameter refer to a file on the local server or the remote server?

**Comment by bjisa** [comment]
I had this same issue, and it's because I was using a key that had a passphrase. I was scratching my head until I saw this issue and @alecho's comment above.

**Comment by holdfenytolvaj** [comment]
there is also a "secret" "forward-agent" option to use the same key for the server and the git

**Comment by findthebrink** [comment]
I've had success running using forward-agent: "yes", however I understand this introduces some security issues. So far I have not been able to deploy from local to remote, even in the case that remote is able to successfully connect to git server and is able to clone when connected via ssh (clone fails when initiated by pm2 from the local machine)

**Comment by holdfenytolvaj** [comment]
As far as i've read the only security issue it exposes, that during the connection is alive, an attacker with privilege to access your socket could execute commands on your behalf on the repo. In case the repo is readonly for the keys, this seems to me a non-issue.

**Comment by NextZeus** [comment]
pm2 seems like that all port is  default  to 22. does it matter?

**Comment by NextZeus** [comment]
ssh-copy-id node@myserver.com

**Comment by Evgeniy28** [comment]
'ssh_options': 'ForwardAgent=yes'

**Comment by mooncfrat2019** [comment]
In my case issue was in permissions to ~/.ssh/config. Just use "chmod 644 on ~/.ssh/config" and add right key to Github/Gitlab. maybe deploy login to ssh by user you provide in config,  but not sure if it try to clone repo by the same user...
