### ISSUE TITLE
SSH port specification doesn't work

### ISSUE THREAD

**Issue by takashi** [Unitech/pm2-deploy#45]
I try deploy my node app with pm2 deploy command 

this is my `ecosystem.json5`

```
{
  /**
   * This is a sample configuration file for PM2
   */

  /**
   * Here we declare the apps that must be managed by PM2
   * All options are listed here:
   * https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#json-app-declaration
   *
   */
  apps : [

    // First application
    {
      name      : "example",
      script    : "server.js",
      env_production : {
        NODE_ENV: "production"
      }
    }
  ],


  /**
   * PM2 help you to deploy apps over your servers
   * For more help go to :
   * https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#deployment-pm2--090
   */
  deploy : {
    production : {
      user : "user",
      host : "HOSTNAME",
      ref  : "origin/master",
      repo : "REPONAME",
      path : "/home/necco/example",
      key  : "PATH_TO_MY_KEY",
      port: 1024
      "post-deploy" : "npm install && npm run server"
    }
  }
}
```

it fails with `sh: connect to host HOSTNAME port 22: Operation timed out`

so port number does not recognized.

I tried with `host: "HOSTNAME -p 1024"` and it is works. 

does `port` option not supported?

**Comment by codydaig** [comment]
After attempting to figure out where the logic was wrong, I finally figured it out. I'm not very familiar with bash, and with the way the bash logic is written in the deploy script the port has to be in quotes. 

So, just putting the port number in quotes should fix it:
port: "1024"

**Comment by takashi** [comment]
@codydaig I tried to do that and it works! thank you for investigating!

**Comment by NextZeus** [comment]
Mark. solved my problem!
