### ISSUE TITLE
Path problem on windows

### ISSUE THREAD

**Issue by whitecolor** [Unitech/pm2-deploy#46]
Running:
> pm2 deploy ecosystem.json production update

on Windows 7 x64 node 0.12, latest pm2

```
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
--> Deploying to production environment
--> on host ...
sh: C:UsersusernameAppDataRoamingnpmnode_modulespm2node_modulespm2-deploy/deploy: No such file or directory
Deploy failed
```

There is some issue with paths to deploy (no slashes)

**Comment by whitecolor** [comment]
Any comment?

**Comment by whitecolor** [comment]
Any comment?

**Comment by simplesmiler** [comment]
Having the same issue.
Looks like most of the path issues on windows were fixed during https://github.com/Unitech/pm2/issues/584, but some still exists.

**Comment by alexei-sch** [comment]
same issue
as a win workaround try to replace
__dirname to __dirname.replace(/\\/g, '/') in deploy.js 'spawn' function

**Comment by whitecolor** [comment]
@alexei-sch there is a PR https://github.com/Unitech/pm2-deploy/pull/47

**Comment by alexei-sch** [comment]
@whitecolor thanks, exactly the same fix)

**Comment by romain10009** [comment]
+1 nice one. Thank you for the fix.

**Comment by whitecolor** [comment]
should be merged and published as bug fix.

**Comment by whitecolor** [comment]
@Unitech this should be merged and published as a bug fix.

**Comment by IIapad0ks** [comment]
+1
