### ISSUE TITLE
Can I deploy my app to multiple envs on the same box?

### ISSUE THREAD

**Issue by k00k** [Unitech/pm2-deploy#48]
I've tried various configurations of ecosystem.json and I'm starting to come to the conclusion that I might need to use multiple ecosystem files to accomplish this (unless I'm missing something). I want to be able to deploy to both staging and production on the same machine with a different port for each env, is this possible?

More detail [here on StackOverflow](http://stackoverflow.com/questions/29923275/using-pm2-how-can-i-deploy-my-node-js-app-to-multiple-environments-and-ports-on)

**Comment by codydaig** [comment]
I don't see an issue with your code off the top of my head. Are you using process.env.PORT to access the PORT variable? The way you have it set-up should work for what your trying to do.

**Comment by Malaar** [comment]
I have the similar issue.
As example. I have already deployed app with name "MyAppName" in production env. After that I need to start the same app in development env on the same host. The problem, that current ecosystem format don't provide ability to setup different names for different environments.

I try to change post-deploy like that:
      "post-deploy" : "pm2 startOrRestart ecosystem.json --env dev --name blueballs-dev"
but it not help me.

It would be useful to have own name for every environments. Example:
{
  "apps" : [{
      "script"    : "blueballs.js",
      "env": {
				"COMMON_ENV_VAR": "true"
      },
      "env_production" : {
        "NODE_ENV": "production"
			},
      "env_dev" : {
        "NODE_ENV": "dev"
      }
	}],
  "deploy" : {
    "production" : {
      "name"      : "blueballs",
       < other standard fields here >
    },
    "dev" : {
      "name"      : "blueballs-dev",
       < other standard fields here >
    }
  }
}

**Comment by spieglio** [comment]
Would be helpful!

**Comment by chazmo03** [comment]
👍

**Comment by thepuzzlemaster** [comment]
I know this is a year old, but it looks like there is a solution posted here: #97

**Comment by vmarchaud** [comment]
You can use now `append_env_to_name: true` inside a process file to tell pm2 to append the env name to your process name (see #2650)
