### ISSUE TITLE
[Feature] supply $PATH to SSH to remote commands to avoid "git not found" when git not available globally

### ISSUE THREAD

**Issue by ieugen** [Unitech/pm2-deploy#52]
Hello, 

I'm using pm2 to deploy an application on a server that I do not own (no root or sudo). I've installed some applications locally, git beeing one of them. I'm having difficulties using pm2 to deploy my app since it the deploy bash script assume "git" command is available and it is not found on the default path. 

For some reason, ssh refuses to read any bash config file (.bashrc, .profile, .bash_profile) and I've tried them all. The only solution so far is to change the deploy script and add a path variable before each git command like:

```
run "PATH=$PATH:~/local/bin git clone $repo $path/source"
```

Any ideas on how to approach this differently?

More info:
```
$ pm2 deploy ecosystem.json production run env
...
PATH=/usr/local/bin:/bin:/usr/bin
....
```

**Comment by ieugen** [comment]
Solution:

I've solved this by adding an export PATH=... at the top of the remote ~/.bashrc file. pm2 deploy uses a non interactive session and reads ~/.bashrc but most distributions have code to skip executing the file if the session is not interactive. 

```
# put things above this line <<<<<
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

**Comment by drtobbyas** [comment]
> Solution:
> 
> I've solved this by adding an export PATH=... at the top of the remote ~/.bashrc file. pm2 deploy uses a non interactive session and reads ~/.bashrc but most distributions have code to skip executing the file if the session is not interactive.
> 
> ```
> # put things above this line <<<<<
> # If not running interactively, don't do anything
> case $- in
>     *i*) ;;
>       *) return;;
> esac
> ```

This solution worked for me
