### ISSUE TITLE
Deploy from my machine to multiple servers

### ISSUE THREAD

**Issue by sean-hill** [Unitech/pm2-deploy#55]
Hey there,

I'd like to deploy the repo on my machine to multiple hosts. I already have this:

	{
		"apps" : [{
			"name"        : "My Server",
			"script"      : "server.js",
			"env": {
				"NODE_ENV": "production"
			}
		}],
		"deploy" : {
			"production" : {
				"user" : "www-data",
				"host" : "1.1.1.1",
				"ref"  : "origin/master",
				"repo" : "git@github.com:example.git",
				"path" : "/var/www/server",
				"post-deploy" : "npm install && pm2 startOrRestart ecosystem.json --env production"
			}
		}
	}

However, I'd like to change my `"host"` to something more like this:

	"host": ["1.1.1.1", "2.2.2.2", "3.3.3.3"]

So that I can deploy the same code base to multiple machines. Is this already possible, or how could I go about doing this with `pm2`?

Thanks for your time.

**Comment by sean-hill** [comment]
It kinda looks like this already exists (here)[https://github.com/Unitech/pm2-deploy/blob/master/deploy.js#L51], am I correct?

**Comment by magestican** [comment]
any updates on this?

**Comment by Unitech** [comment]
Sure it's already available http://pm2.keymetrics.io/docs/usage/deployment/#multi-host-deployment
