### ISSUE TITLE
awkward development

### ISSUE THREAD

**Issue by boneskull** [Unitech/pm2-deploy#71]
So to hack on this thing you actually have to navigate into wherever `pm2` is installed, then overwrite its copy of `pm2-deploy` with your development version.

I had hoped `pm2 install .` would work, but apparently this only works for non-core modules.

This issue probably doesn't belong here, either.

**Comment by davidje** [comment]
are you talking about check_for_local_changes () ?

**Comment by boneskull** [comment]
I don't think so.  going into my `pm2-deploy` working copy and running `pm2 install .` doesn't seem to overwrite the original `pm2-deploy` with my version.

**Comment by Unitech** [comment]
You cannot install pm2-deploy like that, this is not a pm2 module, but a [pm2 dependency](https://github.com/Unitech/pm2/blob/master/lib/CLI/Deploy.js#L5)

If you want to modify it, directly edit the pm2-deploy as a pm2 dependency
