### ISSUE TITLE
Deploy failure

### ISSUE THREAD

**Issue by RiderSx** [Unitech/pm2-deploy#77]
When trying `$ pm2 deploy ecosystem.json dev` getting

```
--> Deploying to dev environment
--> on host 192.168.1.43

  push your changes before deploying

Deploy failed
```

Im getting this even if make full clean of folder to which im deploying and doing `$ pm2 deploy ecosystem.json dev setup`.

It looks very rediculous guys, even after clean deploy setup. What am i supposed to push in just cloned clean local repo with read-only remote repo access?

**Comment by Unitech** [comment]
Could you please type `git status` in your folder and show me the output,

Thanks

**Comment by RiderSx** [comment]
@Unitech
```
# On branch dev
nothing to commit, working directory clean
```

**Comment by Unitech** [comment]
Have you `git push`?

**Comment by RiderSx** [comment]
@Unitech just i said, it's **read-only** access to repo from machine on which is deploying

**Comment by RiderSx** [comment]
There nothing to push because its a freshly cloned repo with no changes at all!

**Comment by Unitech** [comment]
Alright, can you add the option `--force` when doing `pm2 deploy .... --force`

**Comment by RiderSx** [comment]
@Unitech witch `--force` it works

**Comment by Unitech** [comment]
alright! I've added it to the documentation: http://pm2.keymetrics.io/docs/usage/deployment/#force-deployment

**Comment by RiderSx** [comment]
Okay, thank you.
