### ISSUE TITLE
Broken relative path handling causes "deploy log append failed"

### ISSUE THREAD

**Issue by naugtur** [Unitech/pm2-deploy#86]
`$path` can be relative in every single place it's used, except this one
https://github.com/Unitech/pm2-deploy/blob/f0aede676dc87e175f05b1d119571f18c0cdc143/deploy#L233

deploy first does `cd` and then tries to write to `$path/.deploys` so if `$path` is not absolute, it doesn't exist and the script crashes with 
```
bash: myProject/.deploys: No such file or directory

  deploy log append failed

Deploy failed 
```

A quick fix would be to add `../` but please don't do that...
I believe `$path` should be read from the config once and then converted to a full absolute path.

**Comment by gpasq** [comment]
Thanks, just discovered that for myself, but couldn't find this issue again to update it!

**Comment by kichooo** [comment]
Got this issue too. 

Does that mean that I must downgrade or it might be some problem with my ecosystem.json?

**Comment by naugtur** [comment]
I have no idea if downgrading will help. If it worked before then it's worth trying

just set `path` field in ecosystem.json to absolute

**Comment by sbmelvin** [comment]
I'm still experiencing this issue.

```
--> Deploying to dev environment
--> on host secondmind.co
  ○ deploying origin/dev
  ○ executing pre-deploy-local
  ○ hook pre-deploy
  ○ fetching updates
Fetching origin
  ○ resetting HEAD to origin/dev
HEAD is now at 89fd26f Updated ecosystem
bash: dev/.deploys: No such file or directory

  deploy log append failed

Deploy failed
```
