### ISSUE TITLE
how to run multiple envs on one server?

### ISSUE THREAD

**Issue by PavelPolyakov** [Unitech/pm2-deploy#97]
Hi,

As it's stated in the docs:
http://pm2.keymetrics.io/docs/usage/deployment/

```
Process are initialized / started automatically depending on application name in ecosystem.json
```

I want to run several envs on one server:
![image](https://cloud.githubusercontent.com/assets/839290/16485463/2cf5deb4-3ebf-11e6-9480-76ae92530091.png)

On the top of the file I have this:
![image](https://cloud.githubusercontent.com/assets/839290/16485470/3b557528-3ebf-11e6-89d3-68bfed7a0fdd.png)

What it actually means, `pm2` starts the `applications-api` all the time.

How this could be adjusted?

Regards,

**Comment by PavelPolyakov** [comment]
I have found, that we can do this:
```
      "name": "applications-api" + "-" + process.env.NODE_ENV,
```

However, the `NODE_ENV` should be explicitly declared before the `pm2 startOrRestart` execution.
It would be much cooler, if this ENV variable would be taken from the `env` section.

However, probably it's also possible to fix this in other, more convenient, way.

**Comment by Freundschaft** [comment]
@PavelPolyakov where did you put 
`      "name": "applications-api" + "-" + process.env.NODE_ENV,`
?
ecosystem.json is a json file and doesnt allow variables?

Cheers & Thanks!

**Comment by PavelPolyakov** [comment]
json doesn't allow that as standart, that's true. However you can put it like this, because pm2 processes json by itself.However your IDE will try to convince you in the opposite.04.08.2016, 08:16, "Qiong Wu" <notifications@github.com>:@PavelPolyakov where did you put 
"name": "applications-api" + "-" + process.env.NODE_ENV,
?
ecosystem.json is a json file and doesnt allow variables?

Cheers & Thanks!

**Comment by Freundschaft** [comment]
phew, that doesnt sound like a clean solution, but will try thanks!

**Comment by Freundschaft** [comment]
@PavelPolyakov unfortunately it doesnt work I'm always getting 

"applications-api-undefined " as name, and its overwriting the name

**Comment by jybleau** [comment]
hi, that's related to https://github.com/Unitech/pm2-deploy/issues/59

**Comment by jybleau** [comment]
Another solution is to create 2 ecosystem files for 2 environments on the same server.

Then deploy this way:

`pm2 deploy ecosystem.json5 production`

`pm2 deploy ecosystem-test.json5 test`

**Comment by yr0** [comment]
This hasn't been pointed out in the thread, but `pm2 deploy` also accepts JS files - just export the object that you would have put in JSON:
```
// ecosystem.config.js
module.exports = {
  apps: {
    ....
  },
  deploy: {
    ...
  }
}
```

**Comment by bard** [comment]
You can get around the need to pre-declare NODE_ENV by peeking into process.argv (at least as long as the environment is chosen via pm2's `--env` command-line option—I'm not aware of other ways):

```
// ecosystem.config.js

const SUFFIX = process.argv.indexOf('--env') === -1 ? '' :
      '-' + process.argv[process.argv.indexOf('--env')+1]

module.exports = {
    apps: [
        {
            name: 'myapp' + SUFFIX,
            script: 'myapp.js',
            env: {
                NODE_ENV: 'development',
                PORT: 3000
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 3001
            }
        }
    ]
}
```

Then:

```
$ pm2 start ecosystem.config.js
$ pm2 start ecosystem.config.js --env production

┌─────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name                │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├─────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ myapp                   │ 0  │ fork │ 19642 │ online │ 0       │ 5s     │ 0%  │ 56.3 MB   │ disabled │
│ myapp-production        │ 1  │ fork │ 19689 │ online │ 0       │ 0s     │ 0%  │ 16.4 MB   │ disabled │
└─────────────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
```

**Comment by vmarchaud** [comment]
You can use now `append_env_to_name: true` inside a process file to tell pm2 to append the env name to your process name (see #2650)
